# Generated by Django 5.2.5 on 2025-08-28 13:10

from django.db import migrations


'''
def migrate_profiles(apps, schema_editor):
    # Ancien modèle
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    
    # Nouveau modèle
    NewProfile = apps.get_model('profiles', 'Profile')
    
    # Migration des profils
    for old_profile in OldProfile.objects.all():
        new_profile = NewProfile(
            user=old_profile.user,  # conserver la relation avec l'utilisateur
            favorite_city=old_profile.favorite_city
        )
        new_profile.save()
'''

def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        # migrations.RunPython(migrate_profiles),
        migrations.RunPython(noop),
    ]
