# Generated by Django 5.2.5 on 2025-08-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20250828_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Adress', 'verbose_name_plural': 'Adresses'},
        ),
    ]
